[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_function = test_*


markers = 
    smoke:冒烟测试
    cockpit：座舱功能测试
    ai：AI模块测试
    bus：总线测试


addopts = -v --tb=short
